import { Amplify } from 'aws-amplify'

/**
 * What the app needs from amplify_outputs.json beyond the Amplify config.
 * The file is generated by the CDK stack and served next to the app.
 */
export interface DemoConfig {
  region: string
  confidenceThreshold: number
}

export class ConfigError extends Error {}

export function parseConfig(outputs: unknown): DemoConfig {
  const liveness = (outputs as { custom?: { liveness?: Record<string, unknown> } })
    ?.custom?.liveness
  const identityPoolId = (outputs as { auth?: { identity_pool_id?: unknown } })?.auth
    ?.identity_pool_id

  if (typeof identityPoolId !== 'string' || identityPoolId === '') {
    throw new ConfigError('amplify_outputs.json has no auth.identity_pool_id')
  }
  if (typeof liveness?.region !== 'string' || liveness.region === '') {
    throw new ConfigError('amplify_outputs.json has no custom.liveness.region')
  }
  const threshold = Number(liveness.confidence_threshold)
  return {
    region: liveness.region,
    confidenceThreshold: Number.isFinite(threshold) ? threshold : 70,
  }
}

export async function loadConfig(): Promise<DemoConfig> {
  const response = await fetch('/amplify_outputs.json', { cache: 'no-store' })
  if (!response.ok) {
    throw new ConfigError(
      `Could not load /amplify_outputs.json (HTTP ${response.status}). ` +
        'Deploy the stack, or set LIVENESS_SITE_URL to a deployed site when running the dev server.',
    )
  }
  const outputs: unknown = await response.json()
  const config = parseConfig(outputs)
  Amplify.configure(outputs as Parameters<typeof Amplify.configure>[0])
  return config
}
